### ISSUE TITLE
Error in running code

### ISSUE THREAD

**Issue by Rouchestand** [jmhessel/clipscore#11]
Run python clipscore.py example/good_captions.json example/images/
An error occurred as follows：
Traceback (most recent call last):
  File "D:\ConZIC-main\clipscore-main\clipscore.py", line 273, in <module>
    main()
  File "D:\ConZIC-main\clipscore-main\clipscore.py", line 232, in main
    image_feats = extract_all_images(
  File "D:\ConZIC-main\clipscore-main\clipscore.py", line 126, in extract_all_images
    for b in tqdm.tqdm(data):
  File "C:\Users\Prc\anaconda3\envs\pytorch\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "C:\Users\Prc\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\Prc\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Prc\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\Prc\anaconda3\envs\pytorch\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Prc\anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Prc\anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Prc\anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Prc\anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CLIPImageDataset._transform_test.<locals>.<lambda>'

**Comment by jmhessel** [comment]
It looks like you are on a windows machine. I believe that pytorch uses pickle when doing dataloading. And it looks like there's something different about pickle on windows. I don't have much experience working on windows machines, but have you tried looking around for "windows" "pickle" "pytorch dataloader" + "multiprocessing"?

**Comment by Rouchestand** [comment]
Thank you for your warm answer. I have already solved this problem. Set num_ Workers=0
